services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: siakang-backend
    volumes:
      - ./data/logs:/app/data/logs
      - ./data/db:/app/data/db
      - ./data/value:/app/data/value
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: siakang-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend